### ISSUE TITLE
Less song were exported than expected

### ISSUE THREAD

**Issue by Vaarelsauce** [Altrentorae/osuMusicLibExtractor#3]
I'm wondering if the program skips over duplicate song, and if so what kind of criteria does it actually use? 
(artist + title? does it also checks for song duration and other things?)

Also, if it does skip over dupe songs, is it possible to also include a .txt log that shows all the duplicated songs that were skipped instead of being downloaded?

**Comment by Altrentorae** [comment]
It can attempt to skip duplicates, but unfortunately the implementation is very minimal at the moment as it was written for the folder hierarchy method instead of the .ini method that is currently used. Because it relied on the folder hierarchy it simply grabbed the start of a folder name which was normally in format of `[BeatmapSetID] [Artist] - [Title]` Using this method it would mainly check beatmap ID + artist. This was more a workaround for an issue that used to happen with in-game downloads that has since been fixed.

I should just rewrite that entire section of code. I'll make sure to include some more options including a toggle to log stuff to file.

**Comment by Altrentorae** [comment]
Rewrote the section for duplicate checking. More info in release log for [v0.61](https://github.com/Altrentorae/osuMusicLibExtractor/releases/tag/v0.61)
